### ISSUE TITLE
Could not unsign /Applications/Xcode.app

### ISSUE THREAD

**Issue by Merena** [inket/update_xcode_plugins#39] opened 2017-05-12 09:27 UTC
Choose which Xcode you would like to unsign (use arrows): Xcode (8.0) [Signed]: /Applications/Xcode.app
Unsign xcodebuild too?: Yes

Unsigning...

* Changing ownership of /Applications/Xcode.app/Contents/MacOS (will be restored after)
Password:
Assertion failed: (dataoff != 0), function macho_unsign, file unsign.c, line 172.
* Restored ownership of /Applications/Xcode.app/Contents/MacOS
Could not unsign /Applications/Xcode.app
Create an issue on https://github.com/inket/update_xcode_plugins/issues

Do you know why unsign failed?

**Comment by inket** [comment] 2017-05-12 09:30
It seems to be a failure of the unsign tool.

Did you install Xcode 8.0 from the Mac App Store?

I'll give it a go and if I cannot reproduce it, you might need to provide me with your Xcode binary from `/Applications/Xcode.app/Contents/MacOS/Xcode`

**Comment by Merena** [comment] 2017-05-12 09:36
Yes, I install Xcode 8.0 from Mac App Store.
I unsiged yesterday, it successed. Today one of the plugins is not working. So I try to unsiged again, and it failed. I tried many times.

**Comment by inket** [comment] 2017-05-12 09:38
What does running `codesign -vvvv /Applications/Xcode.app/Contents/MacOS/Xcode` return?

**Comment by Merena** [comment] 2017-05-12 09:46
It returns nothing, I wait a long time, then ctrl+C quit it.
$ codesign -vvvv /Applications/Xcode.app/Contents/MacOS/Xcode

^C

**Comment by Merena** [comment] 2017-05-12 09:55
Today I cleaned my Mac using Dr. cleaner, delete a lot of files.  Will it have bad effect on this?
The "codesing" command has output, it excute a long time:
$ codesign -vvvv /Applications/Xcode.app/Contents/MacOS/Xcode 
--prepared:/Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/Versions/Current/.
--validated:/Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/Versions/Current/.
--prepared:/Applications/Xcode.app/Contents/Frameworks/IBFoundation.framework/Versions/Current/.
--validated:/Applications/Xcode.app/Contents/Frameworks/IBFoundation.framework/Versions/Current/.
--prepared:/Applications/Xcode.app/Contents/Frameworks/IDEDocumentation.framework/Versions/Current/.
--validated:/Applications/Xcode.app/Contents/Frameworks/IDEDocumentation.framework/Versions/Current/.
--prepared:/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/Current/.
--validated:/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/Current/.
--prepared:/Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/Current/.
--validated:/Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/Current/.
--prepared:/Applications/Xcode.app/Contents/Frameworks/libclang.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libclang.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libLTO.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libLTO.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftAppKit.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftAppKit.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftAVFoundation.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftAVFoundation.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreAudio.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreAudio.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreData.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreData.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreImage.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreImage.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreMedia.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftCoreMedia.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftDarwin.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftDarwin.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftDispatch.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftDispatch.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftIOKit.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftIOKit.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftObjectiveC.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftObjectiveC.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftos.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftos.dylib
--prepared:/Applications/Xcode.app/Contents/Frameworks/libswiftXPC.dylib
--validated:/Applications/Xcode.app/Contents/Frameworks/libswiftXPC.dylib
--prepared:/Applications/Xcode.app/Contents/Library/Spotlight/uuid.mdimporter
--validated:/Applications/Xcode.app/Contents/Library/Spotlight/uuid.mdimporter
/Applications/Xcode.app/Contents/MacOS/Xcode: invalid Info.plist (plist or signature have been modified)
In subcomponent: /Applications/Xcode.app/Contents/MacOS/Xcode.signed
In architecture: x86_64

**Comment by inket** [comment] 2017-05-12 10:36
Can you run `update_xcode_plugins --restore` then `update_xcode_plugins --unsign` again?

**Comment by Merena** [comment] 2017-05-12 10:39
I just got home, tomorrow I'll goto the company to try it.

发自我的 iPhone

**Comment by inket** [comment] 2017-05-12 10:40
Take your time, nobody should work on a weekend 😜

**Comment by Merena** [comment] 2017-05-13 06:30
This time unsign successed. It means if you have already unsigned, reexcue unsign will be failed. You solve my problem, thank you😀
 

发自我的 iPhone

**Comment by inket** [comment] 2017-05-13 09:27
Usually, running `--unsign` shouldn't show an unsigned Xcode in the list - but I guess `codesign` couldn't read the binary correctly so it detected it as "signed".

Glad you got it resolved. Closing this issue.

**Closed by inket** 2017-05-13 09:27 UTC
Labels: needs input
